# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-14 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=35)),
                ('date', models.DateField(blank=True, max_length=12)),
                ('awarder', models.CharField(blank=True, max_length=70)),
                ('summary', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=70)),
                ('website', models.CharField(blank=True, max_length=40)),
                ('dob', models.DateField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.ManyToManyField(to='resume_builder.Award')),
                ('basics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=70)),
                ('area', models.CharField(max_length=35)),
                ('location', models.CharField(max_length=35)),
                ('branch', models.CharField(max_length=35)),
                ('studyType', models.CharField(max_length=35)),
                ('startDate', models.DateField(max_length=12)),
                ('endDate', models.DateField(max_length=12)),
                ('gpa', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careerObjective', models.CharField(max_length=250)),
                ('totalExperience', models.DateField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35)),
                ('url', models.URLField(blank=True, max_length=40)),
                ('startDate', models.DateField(blank=True, max_length=12)),
                ('endDate', models.DateField(blank=True, max_length=12)),
                ('summary', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, max_length=150)),
                ('Tools', models.CharField(blank=True, max_length=150)),
                ('Platforms', models.CharField(blank=True, max_length=150)),
                ('Services', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=70)),
                ('position', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=35)),
                ('website', models.CharField(blank=True, max_length=35)),
                ('startDate', models.DateField(blank=True, max_length=12)),
                ('endDate', models.DateField(blank=True, max_length=12)),
                ('summary', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='education',
            field=models.ManyToManyField(to='resume_builder.Education'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume_builder.Experience'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='interests',
            field=models.ManyToManyField(to='resume_builder.Interest'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='languages',
            field=models.ManyToManyField(to='resume_builder.Language'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profiles',
            field=models.ManyToManyField(to='resume_builder.Profile'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='projects',
            field=models.ManyToManyField(to='resume_builder.Project'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(to='resume_builder.Skill'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='work',
            field=models.ManyToManyField(to='resume_builder.Work'),
        ),
    ]
