# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-18 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='urls',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
