# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-02 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_auto_20181102_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='endDate',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='education',
            name='startDate',
            field=models.CharField(max_length=4),
        ),
    ]
